### ISSUE TITLE
[Feature] Make-X Darts

### ISSUE THREAD

**Issue by akeith997** [guillaume009/runelite-plugin-action-progress#11]
**Is your feature request related to a problem? Please describe.**
Make-X darts was recently added to OSRS as a toggle in the settings and it would be nice to have this as a progress bar

**Describe the solution you'd like**
A progress bar similar to make-x bolts but for darts

**Comment by guillaume009** [comment]
Will look into it as soon as I get membership again

**Comment by guillaume009** [comment]
Included in the following PR on RuneLite. Should be live soon! I tried putting the best timing as I could for ticks duration, since it isn't documented anywhere. Let me know if it becomes off at some point

https://github.com/runelite/plugin-hub/pull/4787

**Comment by guillaume009** [comment]
Fix was merged, please re-open if the issue persist
