### ISSUE TITLE
[Feature] show ticks instead of seconds

### ISSUE THREAD

**Issue by Jerrk** [guillaume009/runelite-plugin-action-progress#14]
I just personally like seeing ticks instead of seconds and i was hoping we could get an option for that in the plugin.

Thanks!

**Comment by guillaume009** [comment]
Great suggestion, I have added an option that can be enabled in the plugin settings to display ticks instead of seconds. It will go live once the following pull request on runelite is merged 

https://github.com/runelite/plugin-hub/pull/4727
