### ISSUE TITLE
[BUG] Charge Orb with Rune Pouch not showing

### ISSUE THREAD

**Issue by Shajeeb4** [guillaume009/runelite-plugin-action-progress#17]
I noticed when using cosmics inside either the rune pouch or divine rune pouch, the progress bar doesn't show when casting charge orb.

Specifically tested using fire orb charge and with both versions of rune pouches. Screenshots only from when using divine. Tested again with the cosmics outside the pouch and the progress bar showed just fine.

With cosmics inside pouch: 
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/143575466/d7e97c05-3ec1-4d7d-bbd9-091acabb22a0)

With cosmics outside pouch:
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/143575466/2bf2c84e-4ec5-4a64-944e-d5b9218bd4be)

**Comment by guillaume009** [comment]
Should be fixed in RuneLite since last night, can you confirm?

**Comment by guillaume009** [comment]
Author hasn't been responding. Please re-open if the issue remains
