### ISSUE TITLE
add plank make and other things like that if possible[Feature]

### ISSUE THREAD

**Issue by nilmartwitch** [guillaume009/runelite-plugin-action-progress#19]
would it be possible to add plank make enchant jewelry and other things like that if not all good just a nice update if were just afking them

**Comment by guillaume009** [comment]
See #7 for plank make, is it not working? Enchanting jewelry should also already work. There is a new fix since yesterday that now takes into account the rune pouch. Might explain why you didn't see it work before

**Comment by rheine15** [comment]
I can reproduce this. The progress bar does not appear at all when autocasting plank make.

**Comment by nilmartwitch** [comment]
@guillaume009 yes can confirm does not work i can try and get a clip if needed

**Comment by guillaume009** [comment]
No need for a clip. If you could provide the runelite client there might be something that help me figure it out in there

**Comment by guillaume009** [comment]
The linked PR should have fixed this. Please re-opened if that's not the case.
