### ISSUE TITLE
Position not saving across multiple screens

### ISSUE THREAD

**Issue by Ollyeah** [guillaume009/runelite-plugin-action-progress#20]
**Describe the bug**
Position not saving across multiple screens
**To Reproduce**
Move runelite client 
**Expected behavior**
Position to stay the same

**Comment by guillaume009** [comment]
Do you mean when you move the Runelite client between two screens? Are they both the same resolution?

**Comment by Ollyeah** [comment]
Yes, when i switch screens and no two different resolutions

**Comment by guillaume009** [comment]
I think this has to do with how RuneLite itself works. I asked that question because I have had this issue with other plugins too. I'll keep this open in case there is something that can be done about it, but it might not be possible.

**Comment by guillaume009** [comment]
Can't think of a way to do this. If you still want the fix for this ask in RuneLite for how this should be done
