### ISSUE TITLE
[BUG] javelin progress bar

### ISSUE THREAD

**Issue by purush97** [guillaume009/runelite-plugin-action-progress#22]
**Describe the bug**
The progress bar when fletching javelins moves too fast.

**To Reproduce**
1. Click javelin head
2. Click javelin shaft
3. Watch progress bar

**Expected behavior**
Javelins fletch in 10 sets of 15 javelins, 2 ticks each - for a total of 150 javelins across 20 ticks.
The progress bar completes by the time only 6 sets of 15 (90 javelins) have been fletched, after just 12 ticks.

**Screenshots**

**Comment by christopherdk90** [comment]
It seems there is a discrepancy between the game and what is listed on the wiki. 

I was able to reproduce this with bronze, steel, addy, and rune which are all listed as 1-tick on the wiki but are actually 2-tick in game. They were coded with data from the wiki, understandably. 

I don't have the fletching level to test dragon or amethyst but I would suspect they are 2-tick as well (but listed as 1-tick on wiki). If you or anyone else could confirm that, it would be great. But in the meantime I will submit a fix to move all the types to 2-tick.

**Comment by purush97** [comment]
Yeah, amethyst and dragon both are also 2-tick processes, see the attached video link to verify :) thanks for submitting the fix

https://streamable.com/g6fstb

**Comment by guillaume009** [comment]
Fix was merged few weeks back. Closing the issue.
