### ISSUE TITLE
[Feature] Suggestion for a compact mode

### ISSUE THREAD

**Issue by PenguinMeat** [guillaume009/runelite-plugin-action-progress#24]
The UI for this plugin is fantastic when the Runelite client is quite large, but I find that the borders around the action bar are quite bulky when using a smaller Runelite client size like Runescape's fixed mode. The borders end up taking more space than the actual progress bar and when shrunk vertically the progress bar becomes only a pixel tall whereas the borders remain relatively sized.

I suggest having a compact UI mode that removes the transparent borders around the  progress bar and possibly move the text/icons on top of the progress bar to clear up unnecessary screen space.

Example before:
![before](https://github.com/guillaume009/runelite-plugin-action-progress/assets/6394808/ef5ae05c-840e-4104-89d3-155f79998bcc)

Example after:
![after](https://github.com/guillaume009/runelite-plugin-action-progress/assets/6394808/66fd9231-4d90-490f-b01c-2b817a3f121c)

**Comment by guillaume009** [comment]
I like the suggestion. I'll look at it

**Comment by guillaume009** [comment]
You can look forward to this being merged in Runelite soon. This is how it will look. You will only need to resize it

![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8568544/90be992c-cfc4-4c2b-88be-08d2f4af6f8d)
