### ISSUE TITLE
[BUG] Casting sapphire amulet (u) not showing progress

### ISSUE THREAD

**Issue by trzejos** [guillaume009/runelite-plugin-action-progress#34]
**Describe the bug**
As the title says, when casting sapphire ammy (u), the progress overlay does not show up. Noticed this during leagues, usure if main game is affected.

**To Reproduce**
1. Have gold bars + sapphires in inventory w amulet mould
2. craft amulets
3. see no bar

**Expected behavior**
A progress overlay should show up like for other crafting actions

**Comment by kavane12** [comment]
Similar issue with herb cleaning

**Comment by guillaume009** [comment]
@trzejos Noted. It isn't linked to the leagues. That specific recipe must be missing from the plugin. Same thing for @m3atfetish. I'll look into this when I get back in OSRS.


@kavane12 can you elaborate on which herb you see that? Each action must be specifically coded in the plugin so it's possible the one you are talking about is missing

**Comment by guillaume009** [comment]
Fix merged in Runelite for the gold bar. For the herb cleaning please create a different ticket.
