### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by jonathanbyuno** [guillaume009/runelite-plugin-action-progress#39]
**Is your feature request related to a problem? Please describe.**
If you have the smithing outfit, the timer isn't going fast enough to account for the increased speed when smithing items at an anvil.

**Describe the solution you'd like**
Add a checkbox to let the plugin know if you're running the smithing outfit and account for it on the timer.

**Additional context**
[Wiki page of the Smiths' Uniform](https://oldschool.runescape.wiki/w/Smiths%27_Uniform), it states that the whole outfit gives a 100% chance of increasing the speed of a smithing action by 1 tick.

**Comment by guillaume009** [comment]
Added to this repo! Will be merged to Runelite soon
