### ISSUE TITLE
[BUG] Action progress isn't working with creating teleport tablets at a lectern in POH

### ISSUE THREAD

**Issue by HoozH3** [guillaume009/runelite-plugin-action-progress#42]
**Describe the bug**
Action progress isn't working with creating teleport tablets at a lectern in POH

**Comment by guillaume009** [comment]
With that tablet exactly? A fix has been made in the last few days for that, have you seen this behavior recently?

**Comment by HoozH3** [comment]
Hello, thanks for the response and appreciate your work :)
I experienced it yesterday, still isn't showing today not that it's a problem, just really helpful whilst afking knowing at a glance how long is left etc.
See attached, making teleport to house tablets, tried with staff wielded and unweilded, bar not showing with creating tablets setting enabled on the right.
![ActionProgressTabs](https://github.com/guillaume009/runelite-plugin-action-progress/assets/160445731/47c0f869-b9b4-462a-8714-9aef8c7d4211)

**Comment by guillaume009** [comment]
I have found what I believe to be the issue. The lectern I have can't be used to create house teleports, but the name used to check which tablet is being created was wrong in the case of the house teleport.

I have made a pull request to update the plugin on Runelite. It should be merged in 1-2 weeks.

Thank you for reporting the issue 👍
