### ISSUE TITLE
Doesnt work with smiths uniform

### ISSUE THREAD

**Issue by TheLeezen** [guillaume009/runelite-plugin-action-progress#47]
Hello,

The progress bar and timer doesnt work when the smiths uniform is worn, the progress bar ends early, and the progress text cant keep up.¨

Thank you very much for the brilliant plugin

Hope this can be solved

**Comment by guillaume009** [comment]
Change has been made to improve this. It is now merged in Runelite. Please re-open if it's still not accurate
