### ISSUE TITLE
[BUG] Enchanting Bolts without required runes

### ISSUE THREAD

**Issue by patcolyn** [guillaume009/runelite-plugin-action-progress#48]
Progress bar starts when attempting to enchant bolts without the required runes

**Screenshots**
![Image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/13235826/1c1d79a3-2696-4047-ba4e-f9457672694e)

**Comment by guillaume009** [comment]
Change has been made to correct this. It is now merged in Runelite
