### ISSUE TITLE
[Feature] Adding logs to a forester's campfire

### ISSUE THREAD

**Issue by ar1a** [guillaume009/runelite-plugin-action-progress#53]
considering this is such a slow action would love to be able to glance up and see how far into it i am/how long i have left to afk

**Comment by guillaume009** [comment]
Not familiar with the forestry mechanics. I will look into this next time I work on the plugin

**Comment by guillaume009** [comment]
Couldn't find the exact tick values for that action, but I made a change to should match pretty closely. Will come to runelite soon

**Comment by guillaume009** [comment]
Fix is live
