### ISSUE TITLE
[BUG] Progress timers not appearing while enchanting jewelry since spell combo upgrade

### ISSUE THREAD

**Issue by clebauer** [guillaume009/runelite-plugin-action-progress#57]
**Describe the bug**
The normal progress timer that exists in the top left when performing an action doesn't show now that all of the enchant spells have been collapsed into one Enchant Jewelry spell.

**To Reproduce**
1. Have an enchantable piece of jewelry in your inventory, and the appropriate runes to cast it.
2. Click on View Jewellery Enchangements in the Magic menu
3. Click Cast on the spell of your choice.
4. Cast that enchant spell on your jewelry piece of choice.
5. Witness no timer.

**Expected behavior**
I expected to see the progress timer to let me know how long my jewelry would take to enchant.
Note: The progress timer did work moments earlier for making the jewelry, so I know it's not just The Plugin, but this specific issue.

**Screenshots**
<img width="407" alt="image" src="https://github.com/guillaume009/runelite-plugin-action-progress/assets/31354379/3c23b72c-2d2b-4913-8ba9-5f6f82e57206">

<img width="766" alt="image" src="https://github.com/guillaume009/runelite-plugin-action-progress/assets/31354379/628ec20a-3143-4267-89f1-b991ce51ecf5">

<img width="1130" alt="image" src="https://github.com/guillaume009/runelite-plugin-action-progress/assets/31354379/31b34970-9093-49b0-aedd-ae9d3c7fd1fc">

**Comment by NocturnalPvE** [comment]
I'm here to say that this is happening to me as well!

**Comment by guillaume009** [comment]
Yup, I noticed. I made the required change. Just waiting for it to be approved so that the plugin is updated on runelite

**Comment by guillaume009** [comment]
Change has been merged in Runelite
