### ISSUE TITLE
[BUG]ACTION PROGRESS NOT WORKING

### ISSUE THREAD

**Issue by Lewdat95** [guillaume009/runelite-plugin-action-progress#59]
Ive removed it and installed it again. the progress bar does not show up for making herblore potions. im making extended antifires**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by Lewdat95** [comment]
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/165947323/b652a717-7ae2-4e5e-9f93-a080e876fba7)
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/165947323/adfdeae8-0347-46a0-b04e-0f8060aa33b7)

**Comment by guillaume009** [comment]
@Lewdat95 if you moseover the recipe that appear when you try to mix the potion? Trying to see what value the plugin should be looking for

**Comment by Lewdat95** [comment]
Do you mean this? 
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/165947323/87b267b1-6bb3-4fb9-af45-d054f656de13)

**Comment by Lewdat95** [comment]
I sent u a friend request on discord.

**Comment by Lewdat95** [comment]
any ideas?

**Comment by guillaume009** [comment]
I will need to look into it soon, but that should be enough information for me to do so

**Comment by Lewdat95** [comment]
Ok no worries, ty and gl

**Comment by guillaume009** [comment]
Made a tentative fix. Will come to runelite soon

**Comment by guillaume009** [comment]
Fix is live

**Comment by Lewdat95** [comment]
If i reset runelite?

**Comment by guillaume009** [comment]
Yes, you need to restart runelite
