### ISSUE TITLE
Vertical progress bar and smaller version

### ISSUE THREAD

**Issue by CLColdest** [guillaume009/runelite-plugin-action-progress#6]
Hello! 

I wanted to suggest if you can make available the change of the progress bar to a vertical mode and settings to resize it to a smaller version to make it more customizable on gameplay.

thanks I really like the plugin!

**Comment by guillaume009** [comment]
I have changed the code to add support for smaller UI. Here are examples

![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8568544/3e457529-b137-40c6-86a6-5edaf61e824d)

![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8568544/45cbd196-9400-49e5-acdd-1fd0276115fb)


I will close this issue when the plugin is updated on the plugin hub

**Comment by guillaume009** [comment]
New version is live. Closing this issue
