### ISSUE TITLE
[BUG] Incorrect Timing Kebbit Bolts

### ISSUE THREAD

**Issue by coopermor** [guillaume009/runelite-plugin-action-progress#65]
Fletching kebbit spikes into kebbit bolts takes 3 ticks. Action Progress calculates it as 2 ticks so the progress bar ends early.

**Comment by guillaume009** [comment]
Do you know if only the kebbit bolts are off? I can change those, but I wonder if the other ones would need to be changed too. I couldn't find the info on the wiki for the other

**Comment by guillaume009** [comment]
Updated the kebbit bolts timing. The fix is waiting for review on Runelite. Should be live in few days.

**Comment by coopermor** [comment]
I haven't tried, but the wiki does show the sunlight and moonlight bolts being 3 ticks.
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8049699/0ca25330-da79-4075-9970-cea6a42d87c2)
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/8049699/eeab1ba9-52d5-4a0e-a9af-7a4e2c4f6b85)

**Comment by guillaume009** [comment]
Sunlight and moonlight bolts will be included as part of the following change https://github.com/runelite/plugin-hub/pull/6296
