### ISSUE TITLE
[BUG] Cannonballs does not trigger

### ISSUE THREAD

**Issue by alotOSRS** [guillaume009/runelite-plugin-action-progress#66]
**Describe the bug**
Edgeville furnace full inventory of steel bars and the action bar does not appear whether I use space or I click with the mouse.
I disabled every single other plugin and it still does not trigger. When I string magic shortbows the action bar does appear.
I tried both enabling and disabling the smithing cannonballs option in the settings but it simply does not work.

**To Reproduce**
1. Go to Edgeville
2. Click on furnace with steel bars and ammo mould
3. Make cannonballs and see no progress bar

**Expected behavior**
Normally the action bar is supposed to appear.

**Screenshots**
NA

**Comment by guillaume009** [comment]
What type of mould are you using? Works well for me with the double ammo one using either the spacebar or clicking on the option at the Edgeville ufrnace

**Comment by DaLukasDev** [comment]
Maybe the issue here is the small ammo mould. I observe the same issue as @alotOSRS using a normal ammo mould. I do not have the double ammo mould to confirm tho.

**Comment by Woodoki** [comment]
Happening to me at edgevile with a plain ammo mould

**Comment by guillaume009** [comment]
Found the issue. It was specific to the plain ammo mould. Made a fix which is waiting for review on Runelite. Should be live in few days.
