### ISSUE TITLE
[BUG] Using bird nest on a bird nest incorrectly triggers plugin

### ISSUE THREAD

**Issue by clebauer** [guillaume009/runelite-plugin-action-progress#67]
**Describe the bug**
When I use a bird nest on a bird nest, the plugin thinks that the bird nest is being ground.
The nests will not turn into crushed nests (as they properly shouldn't), but the plugin thinks all of the bird nests in the inventory are being ground up,

**To Reproduce**
Use a bird nest on another bird nest while the Action Progress plugin is active.
The nests will not turn into crushed nests (as they shouldn't), but the plugin thinks all of the bird nests in the inventory are being ground up,
 
**Expected behavior**
Nothing should happen.

**Screenshots**
<img width="416" alt="image" src="https://github.com/runelite/runelite/assets/31354379/30b7e3b7-4d9a-4367-a2be-13fb14536bc4">

**Comment by guillaume009** [comment]
Thought I had fixed this before. Changed the code for an alternative way to fix this which is cleaner and hopefully will work better. PR open on Runelite. The fix should be live in couple of days
