### ISSUE TITLE
[BUG] Coal Bag not taken into account for smelting at furnace

### ISSUE THREAD

**Issue by JustenOSRS** [guillaume009/runelite-plugin-action-progress#68]
When smelting at a furnace, if you have an open coal bag, the plugin does not account for the extra coal in the bag.

1. Gather resources to smelt, including enough coal in the coal bag to make an extra bar (for example, 5 runite ore & 27 coal in bag + 26 coal in inventory
2. Smelt at any furnace
3. The plugin will tell you you've finished before you are actually done smelting

**Expected behavior**
The plugin should take into account the amount of coal in the coal bag (27 without cape, 36 with) to determine when you will finish.

**Screenshots**
![image](https://github.com/guillaume009/runelite-plugin-action-progress/assets/170058526/58780b8c-3ab2-4058-a821-afcfc36d6faa)

**Comment by guillaume009** [comment]
Will be included as part of the following change https://github.com/runelite/plugin-hub/pull/6296
