### ISSUE TITLE
[Feature] Plank Make

### ISSUE THREAD

**Issue by JshGrn** [guillaume009/runelite-plugin-action-progress#7]
**Describe the solution you'd like**
Action progress to track plank make when allowing to auto cast

**Additional context**
Waiting for the actions to finish leaves you on the magic tab so you cant see your inventory and know without switching between which is more clicks and not afk, would be great if this plugin could track plank make.

**Comment by guillaume009** [comment]
I have made some changes in the code to support the plank make spell, but I don't have the magic level to test it. The pull request on the plugin hub is open and the change should be merged soon. I'll reply here when it's the case.

**Comment by guillaume009** [comment]
Change as been merged. Let me know if it fixes it

**Comment by guillaume009** [comment]
Closing this since there hasn't been activity. Feel free to re-open if needed
