### ISSUE TITLE
[Feature] Add support for spinning flax into bow strings

### ISSUE THREAD

**Issue by frozencoderdev** [guillaume009/runelite-plugin-action-progress#70]
Is it possible to add progress bars for spinning flax into bow strings? Occasionally on DMM, Leagues, and when I've got time to waste on my iron man I'll spin flax. Progress bars for that action would be nice.

**Comment by guillaume009** [comment]
No problem. Done here 

https://github.com/runelite/plugin-hub/pull/6353

Will be live when it gets merged
