### ISSUE TITLE
[BUG] Plugin prevents spacebar from working during e.g. smithing

### ISSUE THREAD

**Issue by YvesW** [guillaume009/runelite-plugin-action-progress#81]
We've got a couple reports of ``action-progress`` disabling the spacebar from selecting smithing items.

https://discord.com/channels/301497432909414422/442492468307427330/1293059298854703215
https://discord.com/channels/301497432909414422/442492468307427330/1290419473261658182

**Comment by HonkinGoose** [comment]
Turning the plugin on and off a couple times fixed the issue for me. I have yet for it to re-occur, but that's not to say it won't come back

**Comment by guillaume009** [comment]
https://github.com/runelite/plugin-hub/pull/6743
