### ISSUE TITLE
[BUG] Space through chat boxes no longer works

### ISSUE THREAD

**Issue by HonkinGoose** [guillaume009/runelite-plugin-action-progress#83]
**Describe the bug**=

Using space to continue through chat dialogue boxes no longer functions

**To Reproduce**

Any chat box in game will not allow spacebar to continue, not just talking to npc but any in game dialogue box.

Disabling this plugin however remedies the issue

**Expected behavior**
Space to continue through dialogue boxes.

**Screenshots**
N/A

**Comment by guillaume009** [comment]
Would you be able to share the logs of when you are doing that? I want to see if there are any exception since I am not able to reproduce this myself. 

They are located here for Windows C:\Users\<YourUser>\.runelite\logs\client.log

**Comment by HonkinGoose** [comment]
I will be able to do so tonight.

I had noticed it at I believe wintertodt when it tells you you've pulled all your rewards from the crate and thought it was a one off issue due to the new update and it had gotten overlooked.

Then I noticed it again today while fly fishing at the spots just south of priff entrance when it tells you your inventory is to full to catch more. I will try to test more places today and see if I can produce the issue elsewhere.

**Comment by HonkinGoose** [comment]
[client.log](https://github.com/user-attachments/files/17367327/client.log)

**Comment by guillaume009** [comment]
Have you relauched RuneLite recently? I have pushed an update to the plugin to correct an error that I see in your logs

**Comment by HonkinGoose** [comment]
I haven't yet this evening but I will be in about an hour or so. Will update after that.

**Comment by guillaume009** [comment]
It was pushed last Tuesday

**Comment by HonkinGoose** [comment]
Oh yeah I've updated since then. Because I was actually going to submit a bug report about "space to smith last item" not working. Then saw you already had that update ready to push 

But maybe I haven't now that I think about it because after you pushed that update the smithing started working. 

I'll try again tonight.

**Comment by HonkinGoose** [comment]
Client restart solved the issue. I really thought I had restarted since the plugin started working last week.

Apologize for the trouble.
