### ISSUE TITLE
[Feature] Old left/right bar functionality

### ISSUE THREAD

**Issue by jevonsp** [guillaume009/runelite-plugin-action-progress#9]
would it be possible to bring back the old left to right bar filling up as an option?

**Comment by Morcleon** [comment]
You can still set it that way, it's just kind of a pain. You have to start some long action (cannonballs or enchanting or something that gives you some actual time), then you can hold Alt (or whatever key you have set to allow dragging on Runelite) and resize the window manually.

**Comment by guillaume009** [comment]
@Morcleon is correct. I recently added a vertical mode. From your comment. I am assuming it is now defaulting to that vertical mode right? I'll try to find a way to make it use horizontal by default instead

**Comment by jevonsp** [comment]
Yeah it's defaulting to vertical and I couldn't find a toggle, I tried dragging it but I couldn't seem to get the bar to go horizontal progression. 

I honestly don't even mind it now at the default setting but it would be nice to have the option, yeah. Thanks!

**Comment by guillaume009** [comment]
You need to have it up to a certain width before it switch back to horizontal mode (enough for the top text to be written)

**Comment by guillaume009** [comment]
Is it better now? It's hard for me to test default values but I hoping it was fixed with the version I merged few days ago

**Comment by jevonsp** [comment]
Yes it feels much better now! Thanks
